%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-move-base
Version:        1.17.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS move_base package

License:        BSD
URL:            http://wiki.ros.org/move_base
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-actionlib
Requires:       ros-noetic-base-local-planner
Requires:       ros-noetic-clear-costmap-recovery
Requires:       ros-noetic-costmap-2d
Requires:       ros-noetic-dynamic-reconfigure
Requires:       ros-noetic-geometry-msgs
Requires:       ros-noetic-message-runtime
Requires:       ros-noetic-move-base-msgs
Requires:       ros-noetic-nav-core
Requires:       ros-noetic-nav-msgs
Requires:       ros-noetic-navfn
Requires:       ros-noetic-pluginlib
Requires:       ros-noetic-roscpp
Requires:       ros-noetic-rospy
Requires:       ros-noetic-rotate-recovery
Requires:       ros-noetic-std-srvs
Requires:       ros-noetic-tf2-ros
Requires:       ros-noetic-visualization-msgs
BuildRequires:  ros-noetic-actionlib
BuildRequires:  ros-noetic-base-local-planner
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-clear-costmap-recovery
BuildRequires:  ros-noetic-cmake-modules
BuildRequires:  ros-noetic-costmap-2d
BuildRequires:  ros-noetic-dynamic-reconfigure
BuildRequires:  ros-noetic-geometry-msgs
BuildRequires:  ros-noetic-message-generation
BuildRequires:  ros-noetic-move-base-msgs
BuildRequires:  ros-noetic-nav-core
BuildRequires:  ros-noetic-nav-msgs
BuildRequires:  ros-noetic-navfn
BuildRequires:  ros-noetic-pluginlib
BuildRequires:  ros-noetic-roscpp
BuildRequires:  ros-noetic-rospy
BuildRequires:  ros-noetic-rotate-recovery
BuildRequires:  ros-noetic-std-srvs
BuildRequires:  ros-noetic-tf2-geometry-msgs
BuildRequires:  ros-noetic-tf2-ros
BuildRequires:  ros-noetic-visualization-msgs
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
The move_base package provides an implementation of an action (see the actionlib
package) that, given a goal in the world, will attempt to reach it with a mobile
base. The move_base node links together a global and local planner to accomplish
its global navigation task. It supports any global planner adhering to the
nav_core::BaseGlobalPlanner interface specified in the nav_core package and any
local planner adhering to the nav_core::BaseLocalPlanner interface specified in
the nav_core package. The move_base node also maintains two costmaps, one for
the global planner, and one for a local planner (see the costmap_2d package)
that are used to accomplish navigation tasks.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Thu Apr 02 2020 David V. Lu!! <davidvlu@gmail.com> - 1.17.0-1
- Autogenerated by Bloom

