Name:           ros-jade-move-base
Version:        1.13.1
Release:        0%{?dist}
Summary:        ROS move_base package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/move_base
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-actionlib
Requires:       ros-jade-base-local-planner
Requires:       ros-jade-clear-costmap-recovery
Requires:       ros-jade-costmap-2d
Requires:       ros-jade-dynamic-reconfigure
Requires:       ros-jade-geometry-msgs
Requires:       ros-jade-message-runtime
Requires:       ros-jade-move-base-msgs
Requires:       ros-jade-nav-core
Requires:       ros-jade-nav-msgs
Requires:       ros-jade-navfn
Requires:       ros-jade-pluginlib
Requires:       ros-jade-roscpp
Requires:       ros-jade-rospy
Requires:       ros-jade-rotate-recovery
Requires:       ros-jade-std-msgs
Requires:       ros-jade-std-srvs
Requires:       ros-jade-tf
Requires:       ros-jade-visualization-msgs
BuildRequires:  ros-jade-actionlib
BuildRequires:  ros-jade-base-local-planner
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-clear-costmap-recovery
BuildRequires:  ros-jade-cmake-modules
BuildRequires:  ros-jade-costmap-2d
BuildRequires:  ros-jade-dynamic-reconfigure
BuildRequires:  ros-jade-geometry-msgs
BuildRequires:  ros-jade-message-generation
BuildRequires:  ros-jade-move-base-msgs
BuildRequires:  ros-jade-nav-core
BuildRequires:  ros-jade-nav-msgs
BuildRequires:  ros-jade-navfn
BuildRequires:  ros-jade-pluginlib
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-rospy
BuildRequires:  ros-jade-rotate-recovery
BuildRequires:  ros-jade-std-msgs
BuildRequires:  ros-jade-std-srvs
BuildRequires:  ros-jade-tf
BuildRequires:  ros-jade-visualization-msgs

%description
The move_base package provides an implementation of an action (see the actionlib
package) that, given a goal in the world, will attempt to reach it with a mobile
base. The move_base node links together a global and local planner to accomplish
its global navigation task. It supports any global planner adhering to the
nav_core::BaseGlobalPlanner interface specified in the nav_core package and any
local planner adhering to the nav_core::BaseLocalPlanner interface specified in
the nav_core package. The move_base node also maintains two costmaps, one for
the global planner, and one for a local planner (see the costmap_2d package)
that are used to accomplish navigation tasks.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Fri Oct 30 2015 David V. Lu!! <davidvlu@gmail.com> - 1.13.1-0
- Autogenerated by Bloom

* Tue Mar 17 2015 David V. Lu!! <davidvlu@gmail.com> - 1.13.0-0
- Autogenerated by Bloom

