Name:           ros-jade-navigation
Version:        1.13.1
Release:        0%{?dist}
Summary:        ROS navigation package

Group:          Development/Libraries
License:        BSD,LGPL,LGPL (amcl)
URL:            http://wiki.ros.org/navigation
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-jade-amcl
Requires:       ros-jade-base-local-planner
Requires:       ros-jade-carrot-planner
Requires:       ros-jade-clear-costmap-recovery
Requires:       ros-jade-costmap-2d
Requires:       ros-jade-dwa-local-planner
Requires:       ros-jade-fake-localization
Requires:       ros-jade-global-planner
Requires:       ros-jade-map-server
Requires:       ros-jade-move-base
Requires:       ros-jade-move-base-msgs
Requires:       ros-jade-move-slow-and-clear
Requires:       ros-jade-nav-core
Requires:       ros-jade-navfn
Requires:       ros-jade-robot-pose-ekf
Requires:       ros-jade-rotate-recovery
Requires:       ros-jade-voxel-grid
BuildRequires:  ros-jade-catkin

%description
A 2D navigation stack that takes in information from odometry, sensor streams,
and a goal pose and outputs safe velocity commands that are sent to a mobile
base.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Fri Oct 30 2015 David V. Lu!! <davidvlu@gmail.com> - 1.13.1-0
- Autogenerated by Bloom

* Tue Mar 17 2015 David V. Lu!! <davidvlu@gmail.com> - 1.13.0-0
- Autogenerated by Bloom

